### ISSUE TITLE
200 Files limit problem

### ISSUE THREAD

**Issue by misaka00251** [py-radicz/onedrive-sharedfolder-download#3]
Continue discussion of #2.

When a big folder contain lots of files & folders, it will only download the first 200 files & folders. 

For example, I have 10 folders and 200 files in one big shared folder, and I use this script, in the end I only get 10 folders+190 files in total. 

> Example link: https://1drv.ms/u/s!AtZI6E5G7ZC_izG2o7OFNjh2N0Yk?e=hjDg8t

**Comment by py-radicz** [comment]
let me see, if there are any paging options

**Comment by misaka00251** [comment]
Nice! Any updates?

**Comment by py-radicz** [comment]
Working on PR, could you please confirm that the example url you posted contains 352 files currently?

**Comment by py-radicz** [comment]
I just downloaded with work in progress code, and 352 files ends up on my FS, so waiting for confirmation its correct number of files, because onedrive gui does not show me how many files are there

**Comment by py-radicz** [comment]
code base switched backends from asyncio to trio, and also http client lib changed for httpx. As far as I can tell, I am getting all your content downloaded in both cases - using old code, and using latest commit

**Comment by misaka00251** [comment]
Ah now I can't recreate this problem too... But I run into another issue, seems like something wrong with JSON structure?

To avoid copyright infringement I will send more information via Email. But yeah this should be closed now.
