### ISSUE TITLE
Read a excel file 

### ISSUE THREAD

**Issue by Dskpupper** [py-radicz/onedrive-sharedfolder-download#5]
Hey I am new to programming , your script really helped me . As of now the function  downloads  everything in the shared folder . 
But how would a function look if I have to read a particular excel file  among the several files
Thanks appreciate it

**Comment by py-radicz** [comment]
Hello, 

it should be enough if you have direct link to download this excel - just change TLD from `ms` to `ws` and you can directly read content of this file, or pass this edited link to pandas, which could read that excel file as well
